language: go
go:
- 1.11.x
env:
- GO111MODULE=on
script:
- go build .
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: bb9d4bc39fea9c0b8bcc5e1bb532304f51479fdb
  file: "topdownloads"
  on:
    repo: drishtu11/topdownloads
    tags: true
