language: go
go:
- 1.11.x
env:
  matrix:
  - GO111MODULE=on
  global:
  - secure: vUyvU30MS6UgM0EEFcOYsOvI0wcCuAVSURz47l2cVOvHDAGOvGGo39rmjKKlLV1VReiRoRIuQTsg3ZKq1kTBRdnBldQKXC3Otelg9rRtWZLXHc306xHrgF+Wxi8XLxPdHj32uUDnjnxB1BO2fBadA5G4Z3ChMm/kYsqGqAoUnpZ1Rna4vB/QDN3nP+iiWfiNG3Q1jKzgHIyo4ux+srQ2iUkRtaD+wucZIIYV7hpqF/TlPo9fLOGmeDshSh48zWXg3yB+GPiaTvEl9rDTTPnGRF1tRRyqXtEQ3R168iF3TuxfkJg5okshXIAPZI4lY+WijjE7knHSWRHLFMR5dKBSHF4nskKDeHcKpvTVWtlk2GKYp9siier+blgV8yvoIkuo92HHCMDXiDLZqnBwa1jj/cTOIht8efEEAyjB/a6IGiFiOtRIhc0piXefwmQTFCOnR/V955CeUihQKNMpcM8/kahFjnIhMFdKiLHDWKqjcy05ULrt6x9Vqcd6huaDFzbFYTbQgFW6R4B7g6DIZUIpwbwS9d5/DgxPwGMYIUMYMuIs21EFWvw7aO+SJNdYxsVFtZM6oAmk8js0LB/6mxq44mNczbx8FlywMJWr2rMIt2t2JIMAw4ghsTZKLh3CIBAjaXXw0mgG8tigvVcwSOeltzVamSLLKjx62DYZMfqgeqE=
  - secure: xCCcgf79Zi06j3yOMBF0UQW+XxrHWV1X4zUdAz6MKHycJbIRrkLEI9nsoqML+grDVh5iXAdhLgr7Hfl5yrbF7kdngy3StEC0rpDKPw9g+M9OFAip/MipyYmrdgfklhhL6dCORoaDmPeanXyifl7vADV3LQbIei7EuYcGvIDpZJ1E/iUF+YFxHFi0dpGDY4isTkSMQVu4NggghYRyaPYX/38cvyeoeYNzUKNucPpwfyxksavLiAq1cf3gG5OIxFt0lIjsWf/kDPX3LAw4DJYA4A+KAEbe0khxO99agfjQN076qd+0D/MOfyL115gCOyeQiJlBl4BcqmAu6qcbNsqDENffuLgiSKidnOYy8hkpRzZBaDH29VaZCcEPREwj/NZFfEyiD5Wsv9tFq2uxJtNefR4Fsn32Eg3cO2BdSk+6Itvy/PNRqHT+HrYQKuh6OZXt5dLh/7O/Y26KNKgvUvb2qArMQbw+pJL4jUHOcdRvpae3pmGkw2hIK88uYbp4V0EY2xFN20f8d+y8itqLky6Psp2HTPmyRe79HjFqRJQEriPUsD+9fzICd539OjQoRfrKNe/VJqdWjJt/XVVxzgfxiNze6b7EqIJwWJk0ttuo2pqO4yT3YAWvRMJc9HP4mEYTu93Qvhz83pB0PII/yGYL+l8UwRpVTfQvLadeQd5KOgo=
  - secure: Ro6V//zGqyMAl5K0FB340GyMdJRaJfDza31AcuuAIhLx7+4sCbaxyI82eo9K9ikFaeCSvbtx2YS+oFUzTFQ81Ichn7/PYAloZGpf/h9LQgT1ZyGo7JRNk/CVztNnDc7jlnRrLGjenq+04tYyd4Wu7WNg0Hi9EvbJfytIiZ7dyINx9QYi8/o7bHPDOMVcddrkoQZAHD+3Enk8j7G+OI0J0EwiKL/9DlvK38A4n0YRUB7DoS86E97dck+celarfnmxj/iYuo2ef4UqJTjt4bxpOzI8VhItpiTprKrBTkPEhjMLqVawvNvb5S56USU/tMIxbNip65gbjpanDCX6OakRajrWag9OzYHvx0qEm/Keq1qmU9cfS+hEJAuLzA3gIHNKKfwWm6nDDU2fOZm/PPE6UdxI59jYDx9XRWkroSXIgRy4to0NULIe9XzPJVixrT68VmJ+ObAkxA4dMlasPB9IfNivuRT4tQ9KP3w9wrVK8nB71axFXF+rpWIMOlrvbH9RlMC/QoPRVHxKT/PaN1E3l4Yu58FXFPsCUyVxKPYS6tbtwKf8RpejI2do0bvjxGdN8AEOca18pmQnb48Z20uzIuS208ubyJv6OCimZOz5XP4Ttth39yywgZq+2rEGuH+vxBxaW4OTlIfifgZdGO3I5yoPI+bDFPUe30gHRBE5MmM=
script:
- go build .
- go test -v
- "./deploy.sh"
before_deploy: echo 'ready?'
deploy:
  # Build Docker container and push to Docker Hub
  #provider: script
  #script: bash deploy.sh
  #on:
  #  branch: master

  # Deploy to Github releases
  #provider: releases
  #api_key:
  #  secure: o6gbP9PsYQLg9wsEncLwANyqGPQKK5CVrWojDpXBip1U4JbBY2U3ku+WE5Pw16sbiHVN2O+2L+hcSodKWxa6Yq66xM8k7HykC9r9UN0zGXeX+oWEqYZ4SoQ9E+kJHq9rdHgVEIjuCNzV2CeyJaOi1KnTxTB4eMt+d7l49f6lLe8es2DEmCJbI+ooZPk4vazy7KznOSYnJymWV3V05T+glckp776QqlNsSpeOSsXtW5E2DZu7OjkyrsFwvvefyZfJKvcWeAMG7qKfPgpY7xLMn9w0uPqGvi7+epbHYiNNR0iI80MRmmQnEqSWs3agPI8jGD8D+3bXoBdTW1ybqdh/VostyXHXM/GzlQ4EkQ+ok1dD7ad5qzZIn9Vt0oNRbN0PiG+6vpUdG2V+KuFkMnAJ+ZpT+8JkkISY5kIyOthvQkt2jsuP4ZJ6SXgjRZLTB05awnuI2nBWCvecL+UJp0FreR9U8VVXXMrbzMx8Dgn3jy8xc6Yy6DkMTv7GjYqAKW0ImPdpa1gHYq5XDBwk7PUHCqk2JKtBMX1vvUoRnUsqA8xp7OYZVmHtF4oYEG22nixsdY70+wpaeikR3HT0AnRAKV9EEr/C3IlYWPlQblkRuhSTeoU20HKGTaZWFO39LCktsboK5BIV69xLrOCPba+pR5PO9QxR/8RRlxF555s7E+E=
  #file: topdownloads
  #on:
  #  repo: drishtu11/topdownloads
  # Deploy to Heroku
  provider: heroku
  api_key:
    secure: Ro6V//zGqyMAl5K0FB340GyMdJRaJfDza31AcuuAIhLx7+4sCbaxyI82eo9K9ikFaeCSvbtx2YS+oFUzTFQ81Ichn7/PYAloZGpf/h9LQgT1ZyGo7JRNk/CVztNnDc7jlnRrLGjenq+04tYyd4Wu7WNg0Hi9EvbJfytIiZ7dyINx9QYi8/o7bHPDOMVcddrkoQZAHD+3Enk8j7G+OI0J0EwiKL/9DlvK38A4n0YRUB7DoS86E97dck+celarfnmxj/iYuo2ef4UqJTjt4bxpOzI8VhItpiTprKrBTkPEhjMLqVawvNvb5S56USU/tMIxbNip65gbjpanDCX6OakRajrWag9OzYHvx0qEm/Keq1qmU9cfS+hEJAuLzA3gIHNKKfwWm6nDDU2fOZm/PPE6UdxI59jYDx9XRWkroSXIgRy4to0NULIe9XzPJVixrT68VmJ+ObAkxA4dMlasPB9IfNivuRT4tQ9KP3w9wrVK8nB71axFXF+rpWIMOlrvbH9RlMC/QoPRVHxKT/PaN1E3l4Yu58FXFPsCUyVxKPYS6tbtwKf8RpejI2do0bvjxGdN8AEOca18pmQnb48Z20uzIuS208ubyJv6OCimZOz5XP4Ttth39yywgZq+2rEGuH+vxBxaW4OTlIfifgZdGO3I5yoPI+bDFPUe30gHRBE5MmM=
  app: topdownloads
  on:
    repo: drishtu11/topdownloads
after_deploy:
- "./after_deploy.sh"
